package com.rattrapage.microserviceapi.persist.models;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.rattrapage.microserviceapi.utils.FileContentStore;
import lombok.*;
import org.springframework.beans.factory.annotation.Autowired;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Entity(name = "Users")
@Getter
@Setter @NoArgsConstructor @AllArgsConstructor
@Table(name = "users")
//On préfère l'appeler Users plutôt qu'User pour éviter des conflits avec d'autres classes User
//Par défaut hibernate va créer les tables avec une convention de nommage par défaut qui est la plus couremment utilisée
public class Users {



    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    private String username;

    private String pseudo;

    //On respecte le format attendu
    //@JsonFormat(pattern="yyyy-MM-dd")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    private Date createdDate;

    // TODO
    //cette resource n'est visible que si l'utilisateur connecté qui souhaite accéder à l'endpoint en est le propriétaire
    private String email;

    @JsonIgnore
    private String password;

    //@OneToMany(mappedBy = "id", targetEntity = Files.class)
    //@OneToMany(mappedBy = "users", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    //@ManyToMany(cascade = CascadeType.ALL)

    @OneToMany(
            mappedBy = "users",
            cascade = CascadeType.ALL,
            orphanRemoval = true
    )
    @JsonManagedReference
    public List<Files> files = new ArrayList<>();

    public Users(String username, String pseudo, Date createdDate, String email, String password, List<Files> files) {
        this.username = username;
        this.pseudo = pseudo;
        this.createdDate = createdDate;
        this.email = email;
        this.password = password;
        this.files = files;
    }


    public void addFile(Files file) {
        System.out.println("//");
        System.out.println(file.getName());

        files.add(file);
        file.setUsers(this);

    }

    public void removeFileApp(Files file) {
        files.remove(file);
        file.setUsers(null);
    }

    //Getters and setters + constructor generated by lombok


}
