package com.rattrapage.microserviceapi.DTO;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.util.Date;

@Data
public class UserAppDTO {


    // TODO
    // add pattern [
    //[a-zA -Z0 -9_ -]
    private String username;

    private String pseudo;

    // TODO
    //cette resource n'est visible que si l'utilisateur connecté qui souhaite accéder à l'endpoint en est le propriétaire
    private String email;

    private String password;

    //Getters and setters + constructor generated by lombok
}
