package com.rattrapage.microserviceapi.persist.DTO;

import lombok.Data;

@Data
public class UserAppDTO {


    // TODO
    // add pattern [
    //[a-zA -Z0 -9_ -]
    private String username;

    private String pseudo;

    // TODO cette resource n'est visible que si l'utilisateur connecté qui souhaite accéder à l'endpoint en est le propriétaire
    private String email;

    private String password;

    //Getters and setters + constructor generated by lombok
}
